### ISSUE TITLE
Impossible de rejoindre le salon Discord

### ISSUE THREAD

**Issue by tlc28** [Lysquid/Erglace#2]
Bonjour Lysquid,

Je suis désolé d'avoir à utiliser les *issues* du projet pour rentrer en contact
avec toi, mais après avoir essayé avec 3 navigateurs différents, je ne réussis
toujours pas à rejoindre le salon Discord. Je me retrouve devant un message
d'erreur « impossible d'accepter l'invitation ».

Y aurait-il un autre moyen de rejoindre la communauté pour me présenter et
poser quelques questions ? Une liste de diffusion peut-être ? Ou directement ici ?

Je te demande à toi directement, car mes questions sont relatives à la récente
mise à jour de la page Erglace sur le site d'Ergol.

D’avance merci pour ton aide et bonne journée.

-- 
Tanguy

**Comment by Lysquid** [comment]
Bonjour Tanguy,

Je retente de d'inviter avec un nouveau lien : https://discord.com/invite/KW8n3wwn
Tu peux peut être aussi essayer avec l'appli mobile ? Parce que nous n'avons pas trop d'autre endroit où la communauté est présente. Éventuellement Mastodon si tu as : @Lysquid@mastodon.social.
Sinon je suppose que tu peux poser tes questions ici !

**Comment by tlc28** [comment]
> Je retente de d'inviter avec un nouveau lien : https://discord.com/invite/KW8n3wwn

Merci pour l’invitation. Malheureusement, j’ai toujours le même message.

![20240528-092246](https://github.com/Lysquid/Erglace/assets/48520046/83aeada8-ae01-4a83-920a-d09088961ca1)


> Tu peux peut être aussi essayer avec l'appli mobile ?

Elle n’est malheureusement pas disponible dans F-droid. 😞
Je vais regarder si je trouve un contournement.


> Parce que nous n'avons pas trop d'autre endroit où la communauté est présente.
> Éventuellement Mastodon si tu as :
> @[Lysquid@mastodon.social](mailto:Lysquid@mastodon.social).

*ERF*, ma faute, mais je n’ai jamais vraiment franchi le pas des réseaux
sociaux. … pas du tout en fait ! 😅


> Sinon je suppose que tu peux poser tes questions ici !

OK, je me lance, tu vas voir, ce n’est rien de compliqué…

Ça fait 10 ans que je fais du Bépo sur Typematrix. J’en suis plutôt content.
En fait je n’ai pas de problème particulier. Mais, j’ai commencé à réfléchir
à renouveler mon matériel et je me suis dit « pourquoi pas un clavier 3x5 ? ».
Le *hic*, c’est que Bépo n’est pas adapté. Un ami Bépoète m’a parlé d’Ergol,
d’Erglace et de Bépolar. Après une loooongue réflexion, je me suis dit
qu’Erglace était la meilleure alternative des trois pour moi. Mais soudainement,
**BOOM**, la page de présentation d’Erglace change et là, j’ai un doute. 😱
Peut-être ai-je mal interprété la nouvelle section « comment choisir ? », mais
j’ai l’impression que je ne suis plus trop dans la cible !? Résultat, je suis de
retour à la case départ : Ergol, Erglace ou Bépolar ?

Je me dis que, étant donné que tu as conçu la disposition, tu serais le plus à
même de me donner ton avis.

D’avance merci pour ton temps et tes réponses !

**Comment by wismill** [comment]
@tlc28 peux-tu te connecter au [serveur Bépo](https://discord.gg/FzWHzqdW) ? Ergo-L y est également présent.

**Comment by tlc28** [comment]
Merci @wismill pour l’invitation !

Malheureusement, sous Qute, j’ai : 

![20240528-103531](https://github.com/Lysquid/Erglace/assets/48520046/b83686e2-d0be-45de-9fc5-c7661dacd656)

Pas plus de chance sous Firefox : 

![20240528-103714](https://github.com/Lysquid/Erglace/assets/48520046/f4b69be2-999a-4ef8-8baf-da884eb1714e)

Je me demande si je n’ai pas un problème avec le compte Discord que j’ai créé. Je vais essayer d’en créer un autre.

**Comment by Lysquid** [comment]
J'avoue j'étais un peu pessimiste quand j'ai écrit cette page 😂 Je vais peut-être la remodifier parce qu'elle un est un peu trop négative.

De mon point de vue, partagé je crois par la communauté, Ergo-L est actuellement très légèrement meilleur : il a plus de roulements, laisse les raccourcis accessibles, a plus d'utilisateurs, et ses pires enchainements sont moins mauvais. Erglace a lui l'avantage d'un SFB plus faible, et de moins de redirections. Après, le choix dépend bien sûr de chacun⋅e : notamment pour celleux de bépo, qui peuvent préférer garder les voyelles d'un côté.

En fait, je suis moi-même perdu pour aider à choisir, désolé ^^'
Surtout qu'à ce jour, quasi personne n'a appris les deux pour les comparer. Comme le dit Kazé, il n'y a pas de mauvais choix !

Je viens de regarder les stats de Bépolar, elles sont pas exceptionnelles 😅 Si tu as la flemme ou pas le temps d'apprendre ça peut être bien, mais sinon je recommanderais pas.

**Comment by wismill** [comment]
Et en utilisant le lien sur le [site de Bépo](https://bepo.fr/wiki/Contact) ?

En cherchant rapidement sur le web, il semble y avoir plusieurs causes possibles (trop de serveurs, numéro de tél, etc. En tout cas si Bépo ne fonctionne pas non plus cela semble venir de ton côté 🤷

**Comment by tlc28** [comment]
> Et en utilisant le lien sur le [site de Bépo](https://bepo.fr/wiki/Contact) ?

Non, pas mieux.


> En cherchant rapidement sur le web, il semble y avoir plusieurs causes possibles (trop de serveurs, numéro de tél, etc. En tout cas si Bépo ne fonctionne pas non plus cela semble venir de ton côté 🤷

Ça semble en effet être un problème de mon côté. Je vais creuser.

Je dois quand même dire que je ne suis pas vraiment un néophyte de l’Internet et que je suis un peu déçu/surpris par ce premier contact avec Discord. 😞

**Comment by tlc28** [comment]
> J'avoue j'étais un peu pessimiste quand j'ai écrit cette page 😂 Je vais peut-être la remodifier parce qu'elle un est un peu trop négative.

Je confirme que cela se sentait **UN PEU** ! 😅


> De mon point de vue, partagé je crois par la communauté, Ergo-L est
> actuellement très légèrement meilleur :

Je ne suis pas sûr de pouvoir constater la légère différence.


> il a plus de roulements

Je ne suis pas sûr que Bépo soit connu pour ça.


> laisse les raccourcis accessibles

Cela n’entre pas, mais alors pas du tout, dans mes critères de décision !


> a plus d'utilisateurs

*idem*. Je rajouterais « même pas peur ! » 😉


> et ses pires enchainements sont moins mauvais.

Là, j’avoue que j’ai fait la grimace à mon premier « j’ ».


> Erglace a lui l'avantage d'un SFB plus faible, et de moins de
> redirections. Après, le choix dépend bien sûr de chacun⋅e : notamment pour
> celleux de bépo, qui peuvent préférer garder les voyelles d'un côté.

Je suis tout à fait partant pour re-mélanger toutes les lettres ! 😎


> En fait, je suis moi-même perdu pour aider à choisir, désolé ^^'

Par curiosité, tu utilises quelle disposition au quotidien ?


> Surtout qu'à ce jour, quasi personne n'a appris les deux pour les comparer.
> Comme le dit Kazé, il n'y a pas de mauvais choix !

Ça c’est une réponse que me plait !… Elle ne m’aide pas, mais elle me plait ! 😁


> Je viens de regarder les stats de Bépolar, elles sont pas exceptionnelles 😅
> Si tu as la flemme ou pas le temps d'apprendre ça peut être bien, mais sinon je recommanderais pas.

Beaucoup plus utile, merci ! 👍

Je pense que je vais faire quelques sessions de tapotage™ avec Ergol et Erglace et je verrai bien ce que mes doigts en pensent !

Encore merci pour toutes ces informations !

**Comment by Lysquid** [comment]
Content que tu sois pas trop déçu de ma réponse haha.

> Là, j’avoue que j’ai fait la grimace à mon premier « j’ ».

Si tu sens que ça va t'embêter, tu peux appliquer le mod jx, en inversant ces deux lettres. Ça a d'autres défauts, mais moins visibles. Il y a débat si ce mod devient la version officielle ou pas, c'est pas encore tranché.

> Par curiosité, tu utilises quelle disposition au quotidien ?

Erglace tout de même ^^ Et je peux confirmer que c'est sympa ! Mais je viens d'azerty donc j'ai pas de points de comparaison plus pertinent.

> Je pense que je vais faire quelques sessions de tapotage™ avec Ergol et Erglace et je verrai bien ce que mes doigts en pensent !

Bonne méthode, bon tapotage ! :)

Mon sentiment c'est qu'on a pas encore la dispo ultime, Ergo-L et Erglace sont des points d'étape, il faut continuer à expérimenter, créer plus de dispos, et développer la communauté !

**Comment by tlc28** [comment]
> > Là, j’avoue que j’ai fait la grimace à mon premier « j’ ».
> 
> Si tu sens que ça va t'embêter, tu peux appliquer le mod jx, en inversant ces
> deux lettres. Ça a d'autres défauts, mais moins visibles. Il y a débat si ce
> mod devient la version officielle ou pas, c'est pas encore tranché.

Oui, j’avais prévu d’évaluer le mode `jx`.


> > Par curiosité, tu utilises quelle disposition au quotidien ?
> 
> Erglace tout de même ^^ Et je peux confirmer que c'est sympa ! Mais je viens d'azerty donc j'ai pas de points de comparaison plus pertinent.

Soulagement ! 😅

J’avais peur qu’Erglace soit plus un exercice de style qui, finalement, aurait été abandonné.
Mais s’il y a des vrais gens qui l’utilisent, alors je pense que je vais tenter ma chance ! 😎


> Mon sentiment c'est qu'on a pas encore la dispo ultime, Ergo-L et Erglace sont
> des points d'étape, il faut continuer à expérimenter, créer plus de dispos, et
> développer la communauté !

Si ça peut aider, je ferai mes retours d’expérience… dès que j’aurai réussi à faire fonctionner Discord ! 😵

Encore merci pour tous ces retours et à bientôt, je l’espère, pour d’autres discussions !

*case closed*

**Comment by Lysquid** [comment]
> J’avais peur qu’Erglace soit plus un exercice de style qui, finalement, aurait été abandonné.

On doit être 4 à l'utiliser ! :D

> Si ça peut aider, je ferai mes retours d’expérience

Ça serait très utile oui, merci !

À bientôt  ~

**Comment by tlc28** [comment]
> > J’avais peur qu’Erglace soit plus un exercice de style qui, finalement, aurait été abandonné.
> 
> On doit être 4 à l'utiliser ! :D

Cool, ça fera de moi la 5ème roue du carrosse ! 😎… 😅


> > Si ça peut aider, je ferai mes retours d’expérience
> 
> Ça serait très utile oui, merci !

Je m’y mets au mois d’août, pendant les vacances.
Retours en septembre donc…
